apiVersion: batch/v1
kind: Job
metadata:
  name: restore
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: restore
    spec:
      containers:
        - name: restore
          image: schickling/postgres-restore-s3
          imagePullPolicy: Always
          resources:
            requests:
              memory: '100Mi'
              cpu: '100m'
            limits:
              memory: '300Mi'
              cpu: '250m'
          env:
            - name: S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_ACCESS_KEY_ID
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: BUCKET_NAME
            - name: S3_PREFIX
              value: 'backup'
            - name: POSTGRES_DATABASE
              value: prisma-pg
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: pg-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: pg-password
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: database_url
      restartPolicy: Never
