apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
spec:
  # Backup the database every day at 2AM --> 0 2 * * *
  schedule: '54 12 * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: postgres-backup
              image: postgres
              command: ['/bin/sh']
              args:
                [
                  '-c',
                  'echo "$PGPASS" > /root/.pgpass && chmod 600 /root/.pgpass && pg_dump -U postgres -h "postgres-service" "prisma-pg" > /var/backups/backup-now.sql',
                ]
              env:
                - name: PGPASS
                  valueFrom:
                    secretKeyRef:
                      name: pgpass
                      key: pgpass
              volumeMounts:
                - name: postgres-storage
                  mountPath: /var/lib/postgresql/pg-data

                - name: postgres-backups
                  mountPath: /var/backups

          restartPolicy: Never
          volumes:
            - name: postgres-storage
              persistentVolumeClaim:
                claimName: postgres-pv-claim

            - name: postgres-backups
              persistentVolumeClaim:
                claimName: pg-backups-pv-claim
