name: Run Tests and Deploy to Production

on:
  push:
    branches: [master]

jobs:
  Server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.4'

      - uses: marceloprado/has-changed-path@v1
        id: changed-server
        with:
          paths: packages/server packages/common

      - uses: actions/cache@v2
        if: steps.changed-server.outputs.changed == 'true'
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: install dependencies
        if: steps.changed-server.outputs.changed == 'true'
        run: |
          yarn install --frozen-lockfile

      - name: Run Tests
        if: steps.changed-server.outputs.changed == 'true'
        run: |
          cd ./packages/server
          npx jest

      - name: Build Package
        if: steps.changed-server.outputs.changed == 'true'
        run: |
          lerna run build --scope={@devops/common,@devops/server}

      - name: Docker Login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        if: steps.changed-server.outputs.changed == 'true'
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build Server Image
        if: steps.changed-server.outputs.changed == 'true'
        run: |
          yarn build-server-image

      - name: Push Server Image
        if: steps.changed-server.outputs.changed == 'true'
        run: |
          docker push yassineldeeb/graphql:1

      - name: Install Digital Ocean CLI
        if: steps.changed-server.outputs.changed == 'true'
        run: |
          sudo snap install doctl
          sudo snap connect doctl:kube-config
          sudo snap connect doctl:ssh-keys :ssh-keys

      - name: Login to DGO
        if: steps.changed-server.outputs.changed == 'true'
        run: |
          doctl auth init --access-token=${{secrets.DGO_SECRET}}

      - uses: azure/setup-kubectl@v1
        if: steps.changed-server.outputs.changed == 'true'
        id: install

      - name: Saving Cluster Credentials
        if: steps.changed-server.outputs.changed == 'true'
        run: |
          sudo mkdir -m 777 /home/runner/.kube
          doctl kubernetes cluster kubeconfig save graphql-cluster

      - name: Switching Kubectl Context
        if: steps.changed-server.outputs.changed == 'true'
        run: |
          kubectl config use-context do-lon1-graphql-cluster

      - name: Apply Kubernetes Stuff
        if: steps.changed-server.outputs.changed == 'true'
        run: |
          kubectl apply -f ./kubernetes/deployments/graphql-depl.yml
          kubectl apply -f ./kubernetes/deployments/backup-depl.yml
          kubectl scale deployment graphql --replicas=0
          kubectl scale deployment graphql --replicas=2

  Backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.4'

      - uses: marceloprado/has-changed-path@v1
        id: changed-backup
        with:
          paths: packages/backup packages/common

      - uses: actions/cache@v2
        if: steps.changed-backup.outputs.changed == 'true'
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: install dependencies
        if: steps.changed-backup.outputs.changed == 'true'
        run: |
          yarn install --frozen-lockfile

      - name: Build Package
        if: steps.changed-backup.outputs.changed == 'true'
        run: |
          lerna run build --scope={@devops/common,@devops/backup}

      - name: Docker Login
        if: steps.changed-backup.outputs.changed == 'true'
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build Backup Image
        if: steps.changed-backup.outputs.changed == 'true'
        run: |
          yarn build-backup-image

      - name: Push Backup Image
        if: steps.changed-backup.outputs.changed == 'true'
        run: |
          docker push yassineldeeb/pg-backup:1

  Restore:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.4'

      - uses: marceloprado/has-changed-path@v1
        id: changed-restore
        with:
          paths: packages/restore packages/common

      - uses: actions/cache@v2
        if: steps.changed-restore.outputs.changed == 'true'
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: install dependencies
        if: steps.changed-restore.outputs.changed == 'true'
        run: |
          yarn install --frozen-lockfile

      - name: Build Package
        if: steps.changed-restore.outputs.changed == 'true'
        run: |
          lerna run build --scope={@devops/common,@devops/restore}

      - name: Docker Login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        if: steps.changed-restore.outputs.changed == 'true'
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build Restore Image
        if: steps.changed-restore.outputs.changed == 'true'
        run: |
          yarn build-restore-image

      - name: Push Restore Image
        if: steps.changed-restore.outputs.changed == 'true'
        run: |
          docker push yassineldeeb/pg-restore:1
