name: Run Tests and Deploy to Production

on:
  push:
    branches: [master]

jobs:
  Run-tests-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.4'

      - name: Run Tests
        run: |
          cd ./packages/server
          yarn install --frozen-lockfile
          npx jest

      - name: Build Packages
        run: |
          yarn build

      - name: Docker Login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build Server Image
        run: |
          yarn build-server-image

      - name: Build Backup Image
        run: |
          yarn build-backup-image

      - name: Build Restore Image
        run: |
          build-restore-image

      - name: Push Server Image
        run: |
          docker push yassineldeeb/graphql:1

      - name: Push Backup Image
        run: |
          docker push yassineldeeb/pg-backup:1

      - name: Push Restore Image
        run: |
          docker push yassineldeeb/pg-restore:1

      - name: Install Digital Ocean CLI
        run: |
          sudo snap install doctl
          sudo snap connect doctl:kube-config
          sudo snap connect doctl:ssh-keys :ssh-keys

      - name: Login to DGO
        run: |
          doctl auth init --access-token=${{secrets.DGO_SECRET}}

      - uses: azure/setup-kubectl@v1
        id: install

      - name: Saving Cluster Credentials
        run: |
          sudo mkdir -m 777 /home/runner/.kube
          doctl kubernetes cluster kubeconfig save graphql-cluster

      - name: Switching Kubectl Context
        run: |
          kubectl config use-context do-lon1-graphql-cluster

      - name: Apply Kubernetes Stuff
        run: |
          kubectl apply -f ./kubernetes/deployments/graphql-depl.yml
          kubectl apply -f ./kubernetes/deployments/backup-depl.yml
          kubectl scale deployment graphql --replicas=0
          kubectl scale deployment graphql --replicas=2
          kubectl scale deployment backup --replicas=0
          kubectl scale deployment backup --replicas=1
